[package]
name = "d02"
version = "0.1.0"
authors = ["Svante Lidman <svante.lidman@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
